version: '3.9'

services:
  app:
    build:
      context: .
      network: host
    container_name: cleverse-hackathon-backend
    restart: unless-stopped
    depends_on:
      - mongo
    env_file: .env
    ports:
      - 3000:3000

  mongo:
    image: mongo:latest
    container_name: cleverse-hackathon-mongo
    restart: unless-stopped
    ports:
      - 27017:27017
